spring.datasource.url=jdbc:h2:mem:fleurdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.application.name=fleur-service


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
